version: 2
jobs:
  build:
    working_directory: ~/testing-circle-ci
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: unit_test
          command: npm run test
      # - run: # run coverage report
      #    name: code-coverage
      #    command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: coverage
      #     prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml

  deploy_dev:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - run:
          name: deploy-to-aws
          command: echo "deploy to dev stuff would go here" # https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

  deploy_dev_a:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - run:
          name: deploy-to-aws
          command: echo "deploy to dev A stuff would go here"

  run_acceptance_tests:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - run:
          name: deploy-to-aws
          command: echo "Run Acceptance Tests against deployed enviroment to act as gate to prod"

  deploy_prod:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - run:
          name: deploy-to-aws
          command: echo "deploy to prod stuff would go here"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_dev_a:
          requires:
            - deploy_dev
      - run_acceptance_tests:
          requires:
            - deploy_dev_a
      - deploy_prod:
          requires:
            - run_acceptance_tests