project_key         = "iron-comps-frontend"
aws_region          = "us-east-1"
s3_bucket_name      = "iron-comps-frontend-dev"
s3_bucket_env       = "dev"
domain              = "ironcomps.com"
subdomain           = "dev"
hosted_zone         = "ironcomps.com"