project_key         = "iron-comps-frontend"
aws_region          = "us-east-1"
s3_bucket_name      = "iron-comps-frontend-prod"
s3_bucket_env       = "prod"
domain              = "ironcomps.com"
subdomain           = "app"
hosted_zone         = "ironcomps.com"